# Setup
title: Sergey's blog
tagline: Tagline 
paginate: 1
baseurl: ""
permalink: pretty
theme: jekyll-theme-architect

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

page_list:
  About: '/about'
  Home: '/'

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Sergey Shkundaleu 
  url: https://social.ssbx.dev/@archit3ct

# Custom vars
variab: 13
